-- Criando tabela com auto-incremento
CREATE TABLE TAB_IDENTITY (
    ID INT IDENTITY NOT NULL,
    DESCRITOR VARCHAR(20) NULL
);

SELECT * FROM TAB_IDENTITY;

-- inserindo dados
INSERT INTO TAB_IDENTITY (
    DESCRITOR
) VALUES (
    'CLIENTE X'
);
SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (
    DESCRITOR
) VALUES
    ('CLIENTE Y'),
    ('CLIENTE Z'),
    ('CLIENTE W'),
    ('CLIENTE A');

SELECT * FROM TAB_IDENTITY;

-- apagando dados
DELETE FROM TAB_IDENTITY WHERE ID = 1;
SELECT * FROM TAB_IDENTITY;

-- inserindo dados
INSERT INTO TAB_IDENTITY (
    DESCRITOR
) VALUES
    ('CLIENTE B'),
    ('CLIENTE C');

SELECT * FROM TAB_IDENTITY;

-- deletando dados
DELETE FROM TAB_IDENTITY WHERE ID = 6;
SELECT * FROM TAB_IDENTITY;

-- incremento de 5 em 5
CREATE TABLE TAB_IDENTITY2 (
    ID INT IDENTITY (100, 5) NOT NULL,
    DESCRITOR VARCHAR(20) NULL
);

INSERT INTO TAB_IDENTITY2 (
    DESCRITOR 
) VALUES 
    ('CLIENTE Y'),
    ('CLIENTE Z');
SELECT * FROM TAB_IDENTITY2;