--CREATE TABLE PRODUTOS
CREATE TABLE [PRODUTOS]
(
    CODIGO VARCHAR (10) NOT NULL,
    DESCRITOR VARCHAR (100) NULL,
    SABOR VARCHAR (50) NULL,
    TAMANHO VARCHAR (50) NULL,
    EMBALAGEM VARCHAR (50) NULL,
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE [VENDEDORES]
(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAO DATE NULL,
    FERIAS BIT NULL,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE [CLIENTES]
(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    GENERO VARCHAR(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA BIT,
    PRIMARY KEY (CPF)
);

CREATE TABLE [TABELA_DE_VENDAS]
(
    NUMERO VARCHAR(5) NOT NULL,
    DATA_VENDA DATE,
    CPF VARCHAR(11) NOT NULL,
    MATRICULA VARCHAR(5) NOT NULL,
    IMPOSTO FLOAT,
    PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA);

CREATE TABLE [ITENS_VENDIDOS]
(
    NUMERO VARCHAR(5) NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    QUANTIDADE INTEGER,
    PRECO FLOAT,
    PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE ITENS_VENDIDOS
ADD CONSTRAINT FK_TABELA_DE_VENDAS
FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

ALTER TABLE ITENS_VENDIDOS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);