--CREATE TABLE PRODUTOS
CREATE TABLE [PRODUTOS]
(
    CODIGO VARCHAR (10) NOT NULL,
    DESCRITOR VARCHAR (100) NULL,
    SABOR VARCHAR (50) NULL,
    TAMANHO VARCHAR (50) NULL,
    EMBALAGEM VARCHAR (50) NULL,
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE [VENDEDORES]
(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAO DATE NULL,
    FERIAS BIT NULL,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE [CLIENTES]
(
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    GENERO VARCHAR(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA BIT,
    PRIMARY KEY (CPF)
);