SELECT * FROM PRODUTOS;

-- Alterando preço de lista
UPDATE PRODUTOS SET PRECO_LISTA = 5
WHERE CODIGO = '1040107';

SELECT * FROM PRODUTOS;

UPDATE PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.10
WHERE SABOR = 'Manga';

SELECT * FROM PRODUTOS;

-- Alterando tamanho do produto
UPDATE PRODUTOS SET DESCRITOR = REPLACE(DESCRITOR, '350 ml', '550 ml'), TAMANHO = '550 ml'
WHERE SABOR = 'Manga';

SELECT * FROM PRODUTOS WHERE SABOR = 'Manga';

-- Alterando o endereço do cliente
UPDATE CLIENTES SET ENDERECO = 'R. Jorge Emilio 23', BAIRRO = 'Santo Amaro', CIDADE = 'São Paulo', ESTADO = 'SP', CEP = '8833223'
WHERE CPF = '19290992743';

SELECT * FROM CLIENTES WHERE CPF = '19290992743';

-- Alterando o volume de compra
UPDATE CLIENTES SET VOLUME_COMPRA = VOLUME_COMPRA * 1.2
WHERE ESTADO = 'RJ';

SELECT * FROM CLIENTES WHERE ESTADO = 'RJ';
